package com.zccpro.dao;

import com.zccpro.model.ConsumptionLogs;
import java.util.List;

public interface ConsumptionLogsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption_logs
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption_logs
     *
     * @mbg.generated
     */
    int insert(ConsumptionLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption_logs
     *
     * @mbg.generated
     */
    ConsumptionLogs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption_logs
     *
     * @mbg.generated
     */
    List<ConsumptionLogs> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption_logs
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ConsumptionLogs record);
}