package com.zccpro.dao;

import com.zccpro.model.RechargeLogs;
import java.util.List;

public interface RechargeLogsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_logs
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_logs
     *
     * @mbg.generated
     */
    int insert(RechargeLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_logs
     *
     * @mbg.generated
     */
    RechargeLogs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_logs
     *
     * @mbg.generated
     */
    List<RechargeLogs> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_logs
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RechargeLogs record);
}