package com.zccpro.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ConsumptionLogs implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumption_logs.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumption_logs.aid
     *
     * @mbg.generated
     */
    private Integer aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumption_logs.company_code
     *
     * @mbg.generated
     */
    private String companyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumption_logs.buid
     *
     * @mbg.generated
     */
    private String buid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumption_logs.summary
     *
     * @mbg.generated
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumption_logs.consumption_amount
     *
     * @mbg.generated
     */
    private BigDecimal consumptionAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumption_logs.after_balance
     *
     * @mbg.generated
     */
    private BigDecimal afterBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumption_logs.insert_time
     *
     * @mbg.generated
     */
    private Date insertTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table consumption_logs
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumption_logs.id
     *
     * @return the value of consumption_logs.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumption_logs.id
     *
     * @param id the value for consumption_logs.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumption_logs.aid
     *
     * @return the value of consumption_logs.aid
     *
     * @mbg.generated
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumption_logs.aid
     *
     * @param aid the value for consumption_logs.aid
     *
     * @mbg.generated
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumption_logs.company_code
     *
     * @return the value of consumption_logs.company_code
     *
     * @mbg.generated
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumption_logs.company_code
     *
     * @param companyCode the value for consumption_logs.company_code
     *
     * @mbg.generated
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumption_logs.buid
     *
     * @return the value of consumption_logs.buid
     *
     * @mbg.generated
     */
    public String getBuid() {
        return buid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumption_logs.buid
     *
     * @param buid the value for consumption_logs.buid
     *
     * @mbg.generated
     */
    public void setBuid(String buid) {
        this.buid = buid == null ? null : buid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumption_logs.summary
     *
     * @return the value of consumption_logs.summary
     *
     * @mbg.generated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumption_logs.summary
     *
     * @param summary the value for consumption_logs.summary
     *
     * @mbg.generated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumption_logs.consumption_amount
     *
     * @return the value of consumption_logs.consumption_amount
     *
     * @mbg.generated
     */
    public BigDecimal getConsumptionAmount() {
        return consumptionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumption_logs.consumption_amount
     *
     * @param consumptionAmount the value for consumption_logs.consumption_amount
     *
     * @mbg.generated
     */
    public void setConsumptionAmount(BigDecimal consumptionAmount) {
        this.consumptionAmount = consumptionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumption_logs.after_balance
     *
     * @return the value of consumption_logs.after_balance
     *
     * @mbg.generated
     */
    public BigDecimal getAfterBalance() {
        return afterBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumption_logs.after_balance
     *
     * @param afterBalance the value for consumption_logs.after_balance
     *
     * @mbg.generated
     */
    public void setAfterBalance(BigDecimal afterBalance) {
        this.afterBalance = afterBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumption_logs.insert_time
     *
     * @return the value of consumption_logs.insert_time
     *
     * @mbg.generated
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumption_logs.insert_time
     *
     * @param insertTime the value for consumption_logs.insert_time
     *
     * @mbg.generated
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption_logs
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", aid=").append(aid);
        sb.append(", companyCode=").append(companyCode);
        sb.append(", buid=").append(buid);
        sb.append(", summary=").append(summary);
        sb.append(", consumptionAmount=").append(consumptionAmount);
        sb.append(", afterBalance=").append(afterBalance);
        sb.append(", insertTime=").append(insertTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}