package com.zccpro.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class RechargeLogs implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_logs.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_logs.aid
     *
     * @mbg.generated
     */
    private Integer aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_logs.company_code
     *
     * @mbg.generated
     */
    private String companyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_logs.buid
     *
     * @mbg.generated
     */
    private String buid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_logs.summary
     *
     * @mbg.generated
     */
    private BigDecimal summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_logs.recharge_amount
     *
     * @mbg.generated
     */
    private BigDecimal rechargeAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_logs.after_balance
     *
     * @mbg.generated
     */
    private BigDecimal afterBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_logs.insert_time
     *
     * @mbg.generated
     */
    private Date insertTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recharge_logs
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_logs.id
     *
     * @return the value of recharge_logs.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_logs.id
     *
     * @param id the value for recharge_logs.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_logs.aid
     *
     * @return the value of recharge_logs.aid
     *
     * @mbg.generated
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_logs.aid
     *
     * @param aid the value for recharge_logs.aid
     *
     * @mbg.generated
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_logs.company_code
     *
     * @return the value of recharge_logs.company_code
     *
     * @mbg.generated
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_logs.company_code
     *
     * @param companyCode the value for recharge_logs.company_code
     *
     * @mbg.generated
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_logs.buid
     *
     * @return the value of recharge_logs.buid
     *
     * @mbg.generated
     */
    public String getBuid() {
        return buid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_logs.buid
     *
     * @param buid the value for recharge_logs.buid
     *
     * @mbg.generated
     */
    public void setBuid(String buid) {
        this.buid = buid == null ? null : buid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_logs.summary
     *
     * @return the value of recharge_logs.summary
     *
     * @mbg.generated
     */
    public BigDecimal getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_logs.summary
     *
     * @param summary the value for recharge_logs.summary
     *
     * @mbg.generated
     */
    public void setSummary(BigDecimal summary) {
        this.summary = summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_logs.recharge_amount
     *
     * @return the value of recharge_logs.recharge_amount
     *
     * @mbg.generated
     */
    public BigDecimal getRechargeAmount() {
        return rechargeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_logs.recharge_amount
     *
     * @param rechargeAmount the value for recharge_logs.recharge_amount
     *
     * @mbg.generated
     */
    public void setRechargeAmount(BigDecimal rechargeAmount) {
        this.rechargeAmount = rechargeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_logs.after_balance
     *
     * @return the value of recharge_logs.after_balance
     *
     * @mbg.generated
     */
    public BigDecimal getAfterBalance() {
        return afterBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_logs.after_balance
     *
     * @param afterBalance the value for recharge_logs.after_balance
     *
     * @mbg.generated
     */
    public void setAfterBalance(BigDecimal afterBalance) {
        this.afterBalance = afterBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_logs.insert_time
     *
     * @return the value of recharge_logs.insert_time
     *
     * @mbg.generated
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_logs.insert_time
     *
     * @param insertTime the value for recharge_logs.insert_time
     *
     * @mbg.generated
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_logs
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", aid=").append(aid);
        sb.append(", companyCode=").append(companyCode);
        sb.append(", buid=").append(buid);
        sb.append(", summary=").append(summary);
        sb.append(", rechargeAmount=").append(rechargeAmount);
        sb.append(", afterBalance=").append(afterBalance);
        sb.append(", insertTime=").append(insertTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}